In [1]:
import pandas as pd

In [2]:
Homicidios = pd.ExcelFile('C:\\Users\\Dr-Pc\\OneDrive\\Escritorio\\PROYECTO INDIVIDUAL N°2 Siniestros Viales\\homicidios.xlsx')
Homicidios_1 = pd.read_excel(Homicidios, 'HECHOS')
Homicidios_2 = pd.read_excel(Homicidios,'VICTIMAS')

In [3]:
Homicidios_1.rename(columns={'ID': 'ID_hecho'}, inplace=True)

In [4]:
Update_Homicidios = pd.merge(Homicidios_1, Homicidios_2, on='ID_hecho')

In [5]:
Update_Homicidios.head()

,ID_hecho,N_VICTIMAS,FECHA_x,AAAA_x,MM_x,DD_x,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,ACUSADO,FECHA_y,AAAA_y,MM_y,DD_y,ROL,VICTIMA_y,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,AUTO,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,PASAJEROS,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,AUTO,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,SD,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,PASAJEROS,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00

In [6]:
Update_Homicidios.rename(columns={'FECHA_x': 'FECHA'}, inplace=True)
Update_Homicidios.rename(columns={'AAAA_x': 'AAAA'}, inplace=True)
Update_Homicidios.rename(columns={'MM_x': 'MM'}, inplace=True)
Update_Homicidios.rename(columns={'DD_x': 'DD'}, inplace=True)
Update_Homicidios.rename(columns={'VICTIMA_y': 'VICTIMA'}, inplace=True)
Update_Homicidios.rename(columns={'FECHA_FALLECIMIENTO_x': 'FECHA_FALLECIMIENTO'}, inplace=True)

In [30]:
Update_Homicidios.drop('Cruce' , axis = 1, inplace = True)

In [29]:
Update_Homicidios.drop('Calle' , axis = 1, inplace = True)

In [34]:
Update_Homicidios.drop('Dirección Normalizada' , axis = 1, inplace = True)

In [7]:
Update_Homicidios.drop('FECHA_y' , axis = 1, inplace = True)

In [8]:
Update_Homicidios.drop('AAAA_y' , axis = 1, inplace = True)

In [9]:
Update_Homicidios.drop('MM_y' , axis = 1, inplace = True)

In [10]:
Update_Homicidios.drop('DD_y' , axis = 1, inplace = True)

In [11]:
Update_Homicidios.drop('VICTIMA_x' , axis = 1, inplace = True)

In [12]:
Update_Homicidios.drop('Altura' , axis = 1, inplace = True)

In [13]:
Update_Homicidios.head(2)

,ID_hecho,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,XY (CABA),pos x,pos y,PARTICIPANTES,ACUSADO,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,AUTO,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,PASAJEROS,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00

In [14]:
Update_Homicidios['LUGAR_DEL_HECHO'] =Update_Homicidios['LUGAR_DEL_HECHO'].str.replace(',', '')

In [15]:
Update_Homicidios.rename(columns={'HORA': 'HORA_DEL_SINIESTRO'}, inplace=True)

In [16]:
Update_Homicidios['FECHA_FALLECIMIENTO'] = Update_Homicidios['FECHA']

In [17]:
def reorganizar_direcc(address):
    words = address.split()
    if "Av." in words:
        words.remove("Av.")
        words = ["Av."] + words
    return " ".join(words)

Update_Homicidios['LUGAR_DEL_HECHO'] = Update_Homicidios['LUGAR_DEL_HECHO'].apply(reorganizar_direcc)

In [18]:
# Convertir la columna 'FECHA' a objetos datetime
Update_Homicidios['FECHA'] = pd.to_datetime(Update_Homicidios['FECHA'], errors='coerce')

# Formatear la columna 'FECHA' para que muestre solo la fecha en 'YYYY-MM-DD'
Update_Homicidios['FECHA'] = Update_Homicidios['FECHA'].dt.strftime('%Y-%m-%d')

In [19]:
# Convertir la columna 'FECHA' a objetos datetime
Update_Homicidios['FECHA_FALLECIMIENTO'] = pd.to_datetime(Update_Homicidios['FECHA_FALLECIMIENTO'], errors='coerce')

# Formatear la columna 'FECHA' para que muestre solo la fecha en 'YYYY-MM-DD'
Update_Homicidios['FECHA_FALLECIMIENTO'] = Update_Homicidios['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m-%d')

In [20]:
Update_Homicidios.head()

,ID_hecho,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA_DEL_SINIESTRO,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,XY (CABA),pos x,pos y,PARTICIPANTES,ACUSADO,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,AUTO,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,PASAJEROS,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,AUTO,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,SD,CONDUCTOR,MOTO,MASCULINO,18,2016-01-10
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,PASAJEROS,CONDUCTOR,MOTO,MASCULINO,29,2016-01-21

In [21]:
conteo_sd = Update_Homicidios.apply(lambda x: x.value_counts().get('Sd', 0))
#1900-01-14T07:12:00.000
formato_incorrecto = pd.to_datetime(Update_Homicidios['HORA_DEL_SINIESTRO'], errors='coerce').isnull()

#Convertir el formato ISO 8601 a HH:mm:ss
Update_Homicidios.loc[~formato_incorrecto, 'HORA_DEL_SINIESTRO'] = pd.to_datetime(Update_Homicidios.loc[~formato_incorrecto, 'HORA_DEL_SINIESTRO']).dt.strftime('%H:%M:%S')

C:\Users\Dr-Pc\AppData\Local\Temp\ipykernel_12644\459971570.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Update_Homicidios.loc[~formato_incorrecto, 'HORA_DEL_SINIESTRO'] = pd.to_datetime(Update_Homicidios.loc[~formato_incorrecto, 'HORA_DEL_SINIESTRO']).dt.strftime('%H:%M:%S')

In [22]:
Update_Homicidios['pos x'] = Update_Homicidios['pos x'].replace('.', 0.0)
Update_Homicidios['pos y'] = Update_Homicidios['pos y'].replace('.', 0.0)

# Convertir a tipo de dato numérico (opcional, dependiendo de tu necesidad)
Update_Homicidios['pos x'] = pd.to_numeric(Update_Homicidios['pos x'], errors='coerce').astype(float)
Update_Homicidios['pos y'] = pd.to_numeric(Update_Homicidios['pos y'], errors='coerce').astype(float)

In [25]:
Update_Homicidios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_hecho               717 non-null    object
 1   N_VICTIMAS             717 non-null    int64
 2   FECHA                  717 non-null    object
 3   AAAA                   717 non-null    int64
 4   MM                     717 non-null    int64
 5   DD                     717 non-null    int64
 6   HORA_DEL_SINIESTRO     717 non-null    object
 7   HH                     717 non-null    object
 8   LUGAR_DEL_HECHO        717 non-null    object
 9   TIPO_DE_CALLE          717 non-null    object
 10  Calle                  716 non-null    object
 11  Cruce                  540 non-null    object
 12  Dirección Normalizada  708 non-null    object
 13  COMUNA                 717 non-null    int64
 14  XY (CABA)              717 non-null    object
 15  pos x                  717 non-null    float64
 16  pos y                  717 non-null    float64
 17  PARTICIPANTES          717 non-null    object
 18  ACUSADO                717 non-null    object
 19  ROL                    717 non-null    object
 20  VICTIMA                717 non-null    object
 21  SEXO                   717 non-null    object
 22  EDAD                   717 non-null    object
 23  FECHA_FALLECIMIENTO    717 non-null    object
dtypes: float64(2), int64(5), object(17)
memory usage: 134.6+ KB

In [35]:
Update_Homicidios.to_csv('Update_Homicidios.csv', index=False)

In [36]:
Update_Homicidios.head()

,ID_hecho,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA_DEL_SINIESTRO,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,XY (CABA),pos x,pos y,PARTICIPANTES,ACUSADO,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,Point (98896.78238426 93532.43437792),-58.475340,-34.687570,MOTO-AUTO,AUTO,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,Point (95832.05571093 95505.41641999),-58.508775,-34.669777,AUTO-PASAJEROS,PASAJEROS,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,Point (106684.29090040 99706.57687843),-58.390403,-34.631894,MOTO-AUTO,AUTO,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,Point (99840.65224780 94269.16534422),-58.465039,-34.680930,MOTO-SD,SD,CONDUCTOR,MOTO,MASCULINO,18,2016-01-10
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,Point (106980.32827929 100752.16915795),-58.387183,-34.622466,MOTO-PASAJEROS,PASAJEROS,CONDUCTOR,MOTO,MASCULINO,29,2016-01-21